# Generated by Django 6.0.5 on 2026-05-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('COBERTURA', 'Cobertura'), ('TERRENO', 'Terreno'), ('COMERCIAL', 'Comercial')], default='APARTAMENTO', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loja.property')),
            ],
        ),
    ]
