# Generated by Django 6.0.5 on 2026-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_property_property_type_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para exibir este imóvel na seção de destaques'),
        ),
    ]
